
services:
  freeswitch:
    container_name: "freeswitch-community"
    build:
      context: .
      args:
        SIGNALWIRE_TOKEN: ${SIGNALWIRE_TOKEN}
    volumes:
      - ./conf:/etc/freeswitch
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
      net.ipv6.conf.default.disable_ipv6: 1
      net.ipv6.conf.lo.disable_ipv6: 1
    stdin_open: true
    tty: true
    env_file: .env
  # network_mode: "host"
    command: ["freeswitch", "-nonatmap", "-nonat"]
